### ISSUE TITLE
ModuleNotFoundError: No module named 'vtkCommonCorePython'

### ISSUE THREAD

**Issue by wpix** [heprom/pymicro#13]
I cannot seem to import any functions from pymicro due to the following error: ModuleNotFoundError: No module named 'vtkCommonCorePython'

I've tried adding the vtk path to $PYTHONPATH but it still doesn’t work. (https://stackoverflow.com/questions/13495285/importerror-no-module-named-vtkcommonpython)

I am using python3.7 and vtk9.0.1

Your help is much appreciated.

**Comment by heprom** [comment]
This seems like a vtk install problem. we recommend that you create a dedicated anaconda environment where you can install vtk properly. we can try to help on installation problems but we have only limited ressources. one recipe that works at home is:

```
conda create --name pymicro
conda install -c conda-forge -n pymicro vtk=9.0.1 basictools
conda install -n pymicro ipython pytables lxml
conda init bash # only once, use your shell name here
conda activate pymicro
```
