### ISSUE TITLE
Cannot install pymicro

### ISSUE THREAD

**Issue by fzw9381** [heprom/pymicro#14]
My system is Ubuntu 20.04 and the python version is python 3.8.
I tried many times, but couldn't install pymicro.
Can you provide detailed installation steps?

**Comment by heprom** [comment]
Hello,

The best is to create a dedicated environment with conda:

conda create --name pymicro
conda install -c conda-forge -n pymicro vtk=9.0.1 basictools
conda install -n pymicro ipython pytables lxml
conda init bash # only once
git clone https://github.com/heprom/pymicro

The last line checkout the pymicro library. You need to add that folder to the PYTHONPATH. There are 2 ways to do that:
  1. create or update the $PYTHONPATH env variable in you shell, for ex is you use bash: export PYTHONPATH="/path/to/pymicro"
  2. add these two lines at the top of your python script: import sys; sys.path.append('/path/to/pymicro')

now when you start your terminal, you can activate the environment with:
conda activate pymicro.

Let me know if this is working for you
Henry

**Comment by fzw9381** [comment]
Thanks a lot for your help.
However, when I try to install pytables & lxml, it seems something wrong.

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                     

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - backcall -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
  - cached-property -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
  - ipython_genutils -> python[version='>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
  - olefile -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
  - pexpect -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
  - ptyprocess -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0']
  - pyparsing -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - python-dateutil -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - wcwidth -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
  - wheel -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by fzw9381** [comment]
I remove the old environment and retry again.
It works.
Thanks you very much.

**Comment by heprom** [comment]
Glad it worked ! do not hesitate to file other issues as the code is still very much in beta. Sometimes we can react quickly.
