### ISSUE TITLE
An error of example

### ISSUE THREAD

**Issue by fzw9381** [heprom/pymicro#15]
When I run the example atomic_structure_factor.py, the terminal reports an error:

ModuleNotFoundError: No module named'skimage' 

and I cannot install module through conda or pip.

**Comment by heprom** [comment]
Hello,
This is again a dependency installation problem. the package skimage is called scikit-image in the repository, you can install it via conda for your pymicro environment like this:
`conda install -n pymicro scikit-image`

**Comment by heprom** [comment]
I'm closing this issue as it looks resolved to me
