### ISSUE TITLE
No module named 'BasicTools'

### ISSUE THREAD

**Issue by zs1996sjtu** [heprom/pymicro#16]
After I download the pymicro and set PYTHONPATH, I simply run an example of field_ipf.py, and the error occurs: File "../pymicro/pymicro/core/samples.py",line 23, in <module> from BasicTools.Containers.ConstantRectilinearMesh import (
ModuleNotFoundError: No module named ‘BasicTools'

**Comment by heprom** [comment]
Hi,

basictools is a new dependency for pymicro. you can install it using conda:
`conda install -c conda-forge basictools`

Regrads
Henry

**Comment by zs1996sjtu** [comment]
I don’t have anaconda, do you how I can install this package on Ubuntu? Thank you, kind author&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Henry Proudhon ***@***.***&gt;
Date: Wed,Aug 11,2021 5:07 PM
To: heprom/pymicro ***@***.***&gt;
Cc: zs1996sjtu ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [heprom/pymicro] No module named 'BasicTools' (#16)





 
Hi,
 
basictools is a new dependency for pymicro. you can install it using conda:
 conda install -c conda-forge basictools
 
Regrads
 Henry
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by inandi2** [comment]
Hi, 
Has anyone found a solution for this? I am also getting this error.

**Comment by heprom** [comment]
basictools is problematic to install on windows, we are working on this with @basileMarchand and will provide a solution soon.

**Comment by basileMarchand** [comment]
Hello @inandi2, a new version of pymicro has been released. It can be installed via pip and uses a fork of BasicTools that installs correctly on Windows. To install the new version of pymicro and its dependencies, simply run `pip install pymicro`.

Please confirm that it works well for you.

**Comment by heprom** [comment]
I'm closing this issue after commit #26
