### ISSUE TITLE
Pymicro readthedocs page failing to load

### ISSUE THREAD

**Issue by jadball** [heprom/pymicro#20]
Hello,

I'm receiving the following error message when trying to visit [http://pymicro.readthedocs.io/](http://pymicro.readthedocs.io/):

![image](https://user-images.githubusercontent.com/42615415/228243621-96752f3a-511e-4ae7-a4ba-2cf3ad7881c6.png)

It seems like there is some sort of redirect loop, because the URL in my browser changes to this:

`https://pymicro.readthedocs.io/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/projects/pymicro/`

**Comment by AldoMarano** [comment]
Hello, 
This issue has been solved, the documentation website is accessible again ! 

Best,
Aldo
