### ISSUE TITLE
pole figure 3D example

### ISSUE THREAD

**Issue by bma698** [heprom/pymicro#30]
Hello everyone,
I was working on the example "pole figure 3D" and I faced this error,
can anyone guide me for a solution
thanks
![image](https://github.com/user-attachments/assets/1d511e49-2958-4938-8ccf-4749b713a5ee)

**Comment by heprom** [comment]
Thanks for reporting this. This example was not updated for a long time and needed a few changes (see commit 62ef472). It should work now with the `devel` branch.
