### ISSUE TITLE
Method for plotting IFP orientation map

### ISSUE THREAD

**Issue by jadball** [heprom/pymicro#6]
Hello,

I was wondering whether there is a method somewhere within pymicro for plotting an IPF-coloured orientation map of EBSD data loaded into the pymicro.crystal.microstructure.Microstructure class?

Thanks.

**Comment by heprom** [comment]
Hi James,

Thanks for reaching out. Yes, normally a simple `pf.set_map_field('ipf')` should do the trick.
Let me know if you run into some problems.

Henry

**Comment by heprom** [comment]
be careful though, it only works for cubic symmetry for the moment.
